version: '3.5'
services:
  db:
    image: 'mysql:5.7'
    restart: always
    container_name: exemplos-redis-mysql
    volumes:
      - './mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    expose:
      - "3306"
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PWD}

  redis:
    image: redis
    restart: always
    container_name: exemplos-redis-redis
    volumes:
      - './redis:/data'
    command: redis-server --save 60 1 --loglevel warning #--requirepass RedisInsus!
    ports:
      - "6379:6379"
    expose:
      - "6379"
